# Generated by Django 5.2.7 on 2025-11-03 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateField(default=datetime.date(2025, 11, 2)),
            preserve_default=False,
        ),
    ]
